---
- hosts: localhost
  tasks:
  - name: collecting hostname 
    shell: "hostname | tr -d '\n'"
    register: hostname_details 
  - debug:
      var: hostname_details.stdout_lines
  - name: Collecting IP address
    shell: "hostname -I | tr -d '\n'"
    register: ip_details 
  - debug:
      var: ip_details.stdout_lines
  - name: collecting the disk storage output
    shell: "df -h | grep -v 'tmpfs'"
    register: df_details
  - debug:
      var: df_details.stdout_lines  
