---
- hosts: all
  gather_facts: yes
  tasks:
    - name: copy bash scripting to remote machine
      copy:
        src: /home/aadmin/ansible/get_nginx_service_v2.py
        dest: /home/aadmin/get_nginx_service_v2.py
        mode: 0755
        owner: aadmin
        group: aadmin
    - name: Runing the bash script to remote home directory
      shell: python3 /home/aadmin/get_nginx_service_v2.py
      register: command_output
    - debug: 
        var: command_output.stdout_lines

