---
- name: this is example of vars set_facts 
  hosts: localhost
  gather_facts: false
  vars:
    smd: "Sardar Muhammad Danish"
  tasks: 
  - name: this is set_fact example
    set_fact:
      xyz: "alnafi"
  - name: printing the varaible from vars 
    debug:
      var: smd
  - name: print the varaible from wset facts 
    debug:
      var: xyz 

  
